# Copyright (c) Microsoft Corporation MIT license

# Required for schedule trigger
trigger: none
pr: none

schedules:
- cron: '*/10 * * * *'
  displayName: 'Scheduled model sync event'
  branches:
    include: 
    - 'main'
  always: false

pool:
  vmImage: 'ubuntu-20.04'

jobs:

- job: 'evaluate_and_sync_models'
  displayName: 'Evaluate and synchronize models'

  steps:
  - task: Bash@3
    inputs:
      targetType: 'inline'
      script: |
        set -ex
        if [[ -z "$DMR_SYNC_STORAGE" ]]; then
          echo "DMR_SYNC_STORAGE environment variable required for execution. "
          exit 1
        fi

        if [[ -n "$DMR_SYNC_EXPANDED" && "$DMR_SYNC_EXPANDED" == "1" ]]; then
          git clone --single-branch -b 1.0.0-beta.1 https://github.com/Azure/iot-plugandplay-models-tools ../dmrtools
          PATH=../dmrtools:$PATH
          dotnet pack ../dmrtools/clients/dotnet -v m -c Release
          dotnet tool install dmr-client --tool-path ../dmrtools --add-source ../dmrtools/clients/dotnet/Azure.Iot.ModelsRepository.CLI/bin/Release --version 1.0.0-beta.1

          shopt -s globstar
          for file in dtmi/**/*.json; do
            dmr-client export -m $file -o ${file//.json/.expanded.json} --repo $PWD --silent
          done
        fi
    env:
      DMR_SYNC_STORAGE: $(DMR_SYNC_STORAGE)

  - task: AzureCLI@2
    displayName: 'Synchronizing models with storage'
    inputs:
      azureSubscription: $(DMR_SERVICE_CONNECTION)
      scriptType: bash
      scriptLocation: inlineScript
      inlineScript: az storage blob upload-batch -d '$web/dtmi' --account-name $DMR_SYNC_STORAGE -s dtmi --if-unmodified-since 2018-01-01T01:01:01Z --auth-mode login --pattern *.json
    env:
      DMR_SYNC_STORAGE: $(DMR_SYNC_STORAGE)
