name: push_expanded_to_azure_storage

on:
  push:
    branches: [improve_wf]
    paths:
      - 'dtmi/**/*.json'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Pull DMR tools snapshot
        uses: actions/checkout@v2
        with:
          repository: Azure/iot-plugandplay-models-tools
          ref: 1.0.0-beta.1
          path: dmr-tool-cache

      - name: Build and install dmr-client CLI
        run: |
          dotnet pack dmr-tool-cache/clients/dotnet -v q -c Release
          dotnet tool install -g dmr-client --add-source dmr-tool-cache/clients/dotnet/Azure.Iot.ModelsRepository.CLI/bin/Release --version 1.0.0-beta.1
          rm -rf dmr-tool-cache

      - name: Checkout code
        uses: actions/checkout@v2

      - id: files
        uses: digimaun/get-changed-files@v2

      - name: Expand models
        run: |
          set -ex
          for changed_file in ${{ steps.files.outputs.added_modified }}; do
            if [[ ${changed_file} =~ ^dtmi([\/\\][a-z0-9_]+){2,}-([1-9][0-9]{0,8}).json$ ]]; then
              dmr-client export --model-file ${changed_file} --repo $PWD -o ${changed_file//.json/.expanded.json} --silent
            fi
          done
        shell: bash

      - name: CLI push files
        uses: azure/CLI@v1
        with:
          inlineScript: |
            for changed_file in ${{ steps.files.outputs.added_modified }}; do
              if [[ ${changed_file} =~ ^dtmi([\/\\][a-z0-9_]+){2,}-([1-9][0-9]{0,8}).json$ ]]; then
                expanded_file=${changed_file//.json/.expanded.json}

                echo "Submitting ${expanded_file} to Azure Storage"
                az storage blob upload --connection-string "${{ secrets.STORAGE_CONNECTION_STRING }}" --container-name '$web' --name "${expanded_file}" --file "${expanded_file}" --no-progress
              else
                echo "Skipping ${changed_file}. It doesn't appear to be a DTDL document."
              fi
            done
